project_id = "ffmahgphhprqphukcand"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
# The default inbucket can be accessed via http://localhost:54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://ffmahgphhprqphukcand.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.capture-payment]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.create-shopify-product]
verify_jwt = false

[functions.economic-invoice]
verify_jwt = false

[functions.send-chat-email]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-giftcard]
verify_jwt = false

[functions.create-giftcard]
verify_jwt = false

[functions.send-inquiry-email]
verify_jwt = false

[functions.shopify-order-webhook]
verify_jwt = false

[functions.generate-job-title]
verify_jwt = false